test

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,10 +1,12 @@
 #!/bin/sh
 
 # Temporary stash to hold the current state without the staged changes
+echo "stashing changes"
 git stash save -q --keep-index
 
 # Directory to hold the encrypted copies
 temp_dir=$(mktemp -d)
+echo "created tmp directory: $temp_dir"
 
 # Function to clean up temporary files
 cleanup() {
@@ -12,27 +14,28 @@ cleanup() {
     git reset -q HEAD
     git stash pop -q
 }
-trap cleanup EXIT
+# trap cleanup EXIT
 
 FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.\(yaml\|yml\)$')
 
 # Encrypt and replace each staged file
 for file in $FILES; do
     # Copy the staged version to the temporary directory
+    echo "copy the staged version to the temporary directory"
     git show ":$file" > "$temp_dir/$file"
 
     # Run the encryption command here
-    # Replace 'encrypt_command' with your encryption command
+    echo "encrypt temp files"
     sops -e -i "$temp_dir/$file"
 
-    if [ $? -ne 0 ]; then
-        echo "Pre-commit hook failed (command returned error) on file: $file"
-        exit 1
-    fi
+#     if [ $? -ne 0 ]; then
+#         echo "Pre-commit hook failed (command returned error) on file: $file"
+#         exit 1
+#     fi
 
-    # Stage the encrypted file
-    mv "$temp_dir/$file" "$file"
-    git add "$file"
+#     # Stage the encrypted file
+#     mv "$temp_dir/$file" "$file"
+#     git add "$file"
 done
 
 # The script will exit here, the cleanup function will be called automatically
